options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  attribute-quotes:
    - 1
    -
      include: true
  bem-depth: 0
  border-zero:
    - 1
    -
      convention: 'none'
  brace-style:
    - 1
    -
      style: '1tbs'
      allow-single-line: true
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
  clean-import-paths: 2
  declarations-before-nesting: 2
  empty-args:
    - 1
    -
      include: true
  empty-line-between-blocks: 0
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 1
  force-attribute-nesting: 0
  force-element-nesting: 1
  force-pseudo-nesting: 1
  function-name-format:
    - 2
    -
      allow-leading-underscore: false
  hex-length: 0
  hex-notation: 1
  id-name-format:
    - 2
    -
      allow-leading-underscore: false
  indentation: 1
  leading-zero: 1
  max-file-line-count: 0
  max-line-length: 0
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
  mixins-before-declarations: 2
  nesting-depth:
    - 1
    -
      max-depth: 5
  no-at-rule-vendor-prefix: 0
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 2
  no-disallowed-properties: 0
  no-disallowed-property-values: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 2
  no-media-feature-vendor-prefix: 0
  no-mergeable-selectors: 0
  no-misspelled-properties: 2
  no-property-vendor-prefix: 0
  no-qualifying-elements: 0
  no-selector-vendor-prefix: 0
  no-trailing-whitespace: 0
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 0
  no-url-protocols: 0
  no-value-vendor-prefix: 0
  no-warn: 2
  one-declaration-per-line: 0
  placeholder-in-extend: 0
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
  property-sort-order: 0
  property-units: 1
  pseudo-element: 1
  quotes: 0
  shorthand-values: 0
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon: 1
  space-after-comma: 1
  space-around-operator: 1
  space-before-bang: 2
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens: 1
  trailing-semicolon: 1
  url-quotes: 0
  variable-for-property: 0
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
  zero-unit: 2
